const TAX_CODE_REGEX = /^[A-Z0-9]{16}$/
const VAT_NUMBER_REGEX = /^([A-Z]{2}[0-9]{11}|[0-9]{11})$/

export const ENTITY_CONFIGS = [
  {
    key: 'companies',
    label: 'Aziende',
    singularLabel: 'Azienda',
    role: 'Admin',
    readEndpoint: '/api/master-data/companies',
    createEndpoint: '/api/admin-data/companies',
    updateEndpoint: '/api/admin-data/companies',
    deleteEndpoint: '/api/admin-data/companies',
    idField: 'id',
    fields: [
      { name: 'name', label: 'Nome Azienda', type: 'text', required: true, minLength: 2, maxLength: 200, placeholder: 'Es. Acme Industria S.p.A.' },
      { name: 'legalName', label: 'Ragione Sociale', type: 'text', required: false, minLength: 2, maxLength: 250, placeholder: 'Es. ACME SPA' },
      {
        name: 'vatNumber',
        label: 'Partita IVA',
        type: 'text',
        required: false,
        minLength: 11,
        maxLength: 13,
        pattern: VAT_NUMBER_REGEX,
        patternMessage: 'Inserisci 11 cifre o formato IT + 11 cifre.',
        placeholder: 'Es. IT01234567890',
      },
      { name: 'taxCode', label: 'Codice Fiscale', type: 'text', required: false, maxLength: 16, placeholder: 'Es. 00123456789012' },
      { name: 'atecoCode', label: 'Codice ATECO', type: 'text', required: false, maxLength: 10, placeholder: 'Es. 25.62.10' },
      { name: 'activity', label: 'Attività Azienda', type: 'textarea', required: false, maxLength: 500, placeholder: 'Descrizione attività' },
      { name: 'operationalUnitName', label: 'Denominazione Unità Locale', type: 'text', required: false, maxLength: 200 },
      { name: 'type', label: 'Tipologia', type: 'select', required: false, options: [{ value: 'Produzione', label: 'Produzione' }, { value: 'Servizi', label: 'Servizi' }, { value: 'Commercio', label: 'Commercio' }] },
      { name: 'reference', label: 'Riferimento', type: 'text', required: false, maxLength: 120 },
      { name: 'status', label: 'Status', type: 'select', required: false, options: [{ value: 'Attiva', label: 'Attiva' }, { value: 'Archiviata', label: 'Archiviata' }] },
      { name: 'operationalAddress', label: 'Indirizzo Unità Locale', type: 'text', required: false, maxLength: 250 },
      { name: 'operationalCity', label: 'Città Unità Locale', type: 'text', required: false, maxLength: 100 },
      { name: 'operationalPostalCode', label: 'CAP Unità Locale', type: 'text', required: false, maxLength: 10 },
      { name: 'operationalProvince', label: 'Provincia Unità Locale', type: 'text', required: false, maxLength: 100 },
      { name: 'indirizzo SedeLegale', label: 'Indirizzo Sede Legale', type: 'text', required: false, maxLength: 250 },
      { name: 'legalCity', label: 'Città Sede Legale', type: 'text', required: false, maxLength: 100 },
      { name: 'legalPostalCode', label: 'CAP Sede Legale', type: 'text', required: false, maxLength: 10 },
      { name: 'legalProvince', label: 'Provincia Sede Legale', type: 'text', required: false, maxLength: 100 },
      { name: 'country', label: 'Nazione', type: 'text', required: false, maxLength: 100 },
      { name: 'documentStorageLocation', label: 'Luogo Conservazione Documenti', type: 'text', required: false, maxLength: 250 },
      { name: 'usualVisitLocation', label: 'Luogo Abituale Visita', type: 'text', required: false, maxLength: 250 },
      { name: 'clinic', label: 'Ambulatorio', type: 'text', required: false, maxLength: 250 },
      { name: 'communicationsEmail', label: 'Email Comunicazioni', type: 'email', required: false, maxLength: 150 },
      { name: 'billingEmail', label: 'Email Fatturazione', type: 'email', required: false, maxLength: 150 },
      { name: 'pec', label: 'Indirizzo PEC', type: 'email', required: false, maxLength: 150 },
      { name: 'contactPhone', label: 'Telefono', type: 'tel', required: false, maxLength: 30 },
      { name: 'fax', label: 'Fax', type: 'tel', required: false, maxLength: 30 },
      { name: 'internalContactName', label: 'Nome Referente Interno', type: 'text', required: false, maxLength: 120 },
      { name: 'internalContactEmail', label: 'Email Referente Interno', type: 'email', required: false, maxLength: 150 },
      { name: 'externalCode', label: 'Codice Esterno', type: 'text', required: false, maxLength: 50 },
      { name: 'notes', label: 'Note', type: 'textarea', required: false, maxLength: 1000 },
      { name: 'contactEmail', label: 'Email Contatto (legacy)', type: 'email', required: false, maxLength: 150, placeholder: 'Es. hr@azienda.it' },
      { name: 'recipientCode', label: 'Codice Destinatario Fatturazione', type: 'text', required: false, maxLength: 10 },
      { name: 'contractIdentifier', label: 'Identificativo Contratto', type: 'text', required: false, maxLength: 50 },
      { name: 'orderCode', label: 'Codice Commessa', type: 'text', required: false, maxLength: 50 },
      { name: 'cupCode', label: 'Codice CUP', type: 'text', required: false, maxLength: 50 },
      { name: 'cigCode', label: 'Codice CIG', type: 'text', required: false, maxLength: 50 },
      { name: 'paymentTerms', label: 'Condizioni Pagamento', type: 'select', required: false, options: [{ value: 'Immediato', label: 'Immediato' }, { value: '30gg', label: '30 giorni' }, { value: '60gg', label: '60 giorni' }] },
      { name: 'paymentMethod', label: 'Modalità Pagamento', type: 'select', required: false, options: [{ value: 'Bonifico', label: 'Bonifico' }, { value: 'RID', label: 'RID' }, { value: 'Assegno', label: 'Assegno' }] },
      { name: 'accountHolder', label: 'Intestatario', type: 'text', required: false, maxLength: 150 },
      { name: 'bankName', label: 'Istituto Bancario', type: 'text', required: false, maxLength: 150 },
      { name: 'iban', label: 'IBAN', type: 'text', required: false, maxLength: 34 },
      { name: 'bicSwift', label: 'BIC/Swift', type: 'text', required: false, maxLength: 11 },
      { name: 'abi', label: 'ABI', type: 'text', required: false, maxLength: 5 },
      { name: 'cab', label: 'CAB', type: 'text', required: false, maxLength: 5 },
      { name: 'intentLetterNumber', label: 'Numero Lettera Intenti', type: 'text', required: false, maxLength: 50 },
      { name: 'intentLetterDate', label: 'Data Lettera Intenti', type: 'date', required: false },
      { name: 'intentLetterExpiry', label: 'Scadenza Lettera Intenti', type: 'date', required: false },
      { name: 'bankChargesDebit', label: 'Addebito Spese Bancarie', type: 'text', required: false, maxLength: 200 },
      { name: 'bankChargesAmount', label: 'Importo Spese Bancarie', type: 'number', required: false, min: 0, placeholder: '0' },
      { name: 'splitPayment', label: 'Split Payment', type: 'text', required: false, maxLength: 50 },
    ],
  },
  {
    key: 'branches',
    label: 'Sedi',
    singularLabel: 'Sede',
    role: 'Admin',
    readEndpoint: '/api/master-data/branches',
    createEndpoint: '/api/admin-data/branches',
    updateEndpoint: '/api/admin-data/branches',
    deleteEndpoint: '/api/admin-data/branches',
    idField: 'id',
    fields: [
      { name: 'companyId', label: 'Azienda', type: 'select', required: true, optionsEndpoint: '/api/master-data/companies', optionValue: 'id', optionLabel: 'name' },
      { name: 'address', label: 'Indirizzo', type: 'text', required: true, minLength: 5, maxLength: 250, placeholder: 'Es. Via Roma 10' },
      { name: 'city', label: 'Città', type: 'text', required: true, minLength: 2, maxLength: 100, placeholder: 'Es. Milano' },
      { name: 'province', label: 'Provincia', type: 'text', required: false, maxLength: 100, placeholder: 'Es. MI' },
      { name: 'postalCode', label: 'CAP', type: 'text', required: false, maxLength: 10, placeholder: 'Es. 20100' },
    ],
  },
  {
    key: 'employees',
    label: 'Dipendenti',
    singularLabel: 'Dipendente',
    role: 'Admin',
    readEndpoint: '/api/master-data/employees',
    createEndpoint: '/api/admin-data/employees',
    updateEndpoint: '/api/admin-data/employees',
    deleteEndpoint: '/api/admin-data/employees',
    idField: 'id',
    fields: [
      { name: 'companyId', label: 'Azienda', type: 'select', required: true, optionsEndpoint: '/api/master-data/companies', optionValue: 'id', optionLabel: 'name' },
      { name: 'branchId', label: 'Sede', type: 'select', required: true, optionsEndpoint: '/api/master-data/branches', optionValue: 'id', optionLabel: 'address' },
      { name: 'firstName', label: 'Nome', type: 'text', required: true, minLength: 2, maxLength: 120, placeholder: 'Es. Mario' },
      { name: 'lastName', label: 'Cognome', type: 'text', required: true, minLength: 2, maxLength: 120, placeholder: 'Es. Rossi' },
      { name: 'matricola', label: 'Matricola', type: 'text', required: false, maxLength: 50 },
      { name: 'birthDate', label: 'Data di Nascita', type: 'date', required: true },
      {
        name: 'gender',
        label: 'Sesso',
        type: 'select',
        required: true,
        options: [
          { value: 'M', label: 'Maschio' },
          { value: 'F', label: 'Femmina' },
        ],
      },
      { name: 'birthCity', label: 'Comune di Nascita', type: 'text', required: true, minLength: 2, maxLength: 120, placeholder: 'Es. Milano' },
      {
        name: 'birthCityCode',
        label: 'Codice Comune',
        type: 'text',
        hiddenInForm: true,
        required: true,
        minLength: 4,
        maxLength: 4,
        pattern: /^[A-Z][0-9]{3}$/,
        patternMessage: 'Formato atteso: una lettera e tre numeri (es. F205).',
        placeholder: 'Es. F205',
        transform: (value) => value.toUpperCase(),
      },
      {
        name: 'taxCode',
        label: 'Codice Fiscale',
        type: 'text',
        required: true,
        minLength: 16,
        maxLength: 16,
        pattern: TAX_CODE_REGEX,
        patternMessage: 'Il codice fiscale deve avere 16 caratteri alfanumerici.',
        placeholder: 'Es. RSSMRA80A01F205X',
        transform: (value) => value.toUpperCase(),
      },
      { name: 'nazionalita', label: 'Nazionalità', type: 'text', required: false, maxLength: 100 },
      { name: 'domicilio', label: 'Domicilio', type: 'text', required: false, maxLength: 250 },
      { name: 'indirizzoDomicilio', label: 'Indirizzo Domicilio', type: 'text', required: false, maxLength: 250 },
      { name: 'jobRole', label: 'Mansione', type: 'text', required: true, minLength: 2, maxLength: 120, placeholder: 'Es. Operatore linea' },
      { name: 'personalEmail', label: 'Email Personale', type: 'email', required: false, maxLength: 150, placeholder: 'Es. nome.cognome@email.it' },
      { name: 'phoneNumber', label: 'Telefono', type: 'tel', required: false, maxLength: 30, placeholder: 'Es. +39 333 1234567' },
      { name: 'medicoCarante', label: 'Medico Curante', type: 'text', required: false, maxLength: 150 },
      { name: 'indirizzoMedico', label: 'Indirizzo Medico', type: 'text', required: false, maxLength: 250 },
      { name: 'telefonoMedico', label: 'Telefono Medico', type: 'tel', required: false, maxLength: 30 },
      { name: 'gruppoSanguigno', label: 'Gruppo Sanguigno', type: 'select', required: false, options: [{ value: 'A+', label: 'A+' }, { value: 'A-', label: 'A-' }, { value: 'B+', label: 'B+' }, { value: 'B-', label: 'B-' }, { value: 'AB+', label: 'AB+' }, { value: 'AB-', label: 'AB-' }, { value: '0+', label: '0+' }, { value: '0-', label: '0-' }] },
      { name: 'dataUltimaVisita', label: 'Data Ultima Visita', type: 'date', required: false },
      { name: 'periodicita', label: 'Periodicità', type: 'select', required: false, options: [{ value: 'Annuale', label: 'Annuale' }, { value: 'Biennale', label: 'Biennale' }, { value: 'Triennale', label: 'Triennale' }] },
      { name: 'dataProssimaVisita', label: 'Data Prossima Visita', type: 'date', required: false },
      { name: 'tipoProssimaVisita', label: 'Tipo Prossima Visita', type: 'select', required: false, options: [{ value: 'Periodica', label: 'Periodica' }, { value: 'Preventiva', label: 'Preventiva' }] },
      { name: 'reparto', label: 'Reparto', type: 'text', required: false, maxLength: 120 },
      { name: 'luogoDiLavoro', label: 'Luogo di Lavoro', type: 'text', required: false, maxLength: 250 },
      { name: 'dataUltimaVisitaRI', label: 'Data Ultima Visita RI', type: 'date', required: false },
      { name: 'periodicitaVisitaRI', label: 'Periodicità Visita RI', type: 'select', required: false, options: [{ value: 'Annuale', label: 'Annuale' }, { value: 'Biennale', label: 'Biennale' }] },
      { name: 'dataProssimaVisitaRI', label: 'Data Prossima Visita RI', type: 'date', required: false },
      { name: 'dataAssunzione', label: 'Data Assunzione', type: 'date', required: false },
      { name: 'dataAttualeMansione', label: 'Data Attuale Mansione', type: 'date', required: false },
      { name: 'referenteAziendale', label: 'Referente Aziendale', type: 'text', required: false, maxLength: 150 },
      { name: 'identificativoMPI', label: 'Identificativo MPI', type: 'text', required: false, maxLength: 50 },
      { name: 'statoRisorsa', label: 'Stato Risorsa', type: 'select', required: false, options: [{ value: 'Attivo', label: 'Attivo' }, { value: 'Cessato', label: 'Cessato' }, { value: 'Sospeso', label: 'Sospeso' }] },
      { name: 'motivazione', label: 'Motivazione', type: 'text', required: false, maxLength: 250 },
      { name: 'dataCessazione', label: 'Data Cessazione/Assenza', type: 'date', required: false },
      { name: 'dataRiattivazione', label: 'Data Riattivazione', type: 'date', required: false },
      { name: 'categoriaProtetta', label: 'Categoria Protetta', type: 'text', required: false, maxLength: 100 },
      { name: 'documentiPrivacy', label: 'Documenti Privacy Raccolti', type: 'text', required: false, maxLength: 250 },
      { name: 'noteRiservate', label: 'Note Riservate', type: 'textarea', required: false, maxLength: 1000 },
      { name: 'notePerAzienda', label: 'Note per Azienda', type: 'textarea', required: false, maxLength: 1000 },
    ],
  },
  {
    key: 'risk-factors',
    label: 'Fattori di Rischio',
    singularLabel: 'Fattore di Rischio',
    role: 'Admin',
    readEndpoint: '/api/master-data/risk-factors',
    createEndpoint: '/api/admin-data/risk-factors',
    updateEndpoint: '/api/admin-data/risk-factors',
    deleteEndpoint: '/api/admin-data/risk-factors',
    idField: 'id',
    fields: [
      { name: 'name', label: 'Nome Rischio', type: 'text', required: true, minLength: 2, maxLength: 120, placeholder: 'Es. Rumore' },
      { name: 'description', label: 'Descrizione', type: 'textarea', required: true, minLength: 10, maxLength: 500, placeholder: 'Descrivi il rischio, esposizione e contesto operativo...' },
      { name: 'severityLevel', label: 'Livello Severità (1-5)', type: 'number', required: true, min: 1, max: 5, placeholder: 'Es. 3' },
      { name: 'allegato3BCategory', label: 'Categoria Allegato 3B', type: 'text', required: false, maxLength: 120, placeholder: 'Es. Agenti fisici' },
    ],
  },
  {
    key: 'job-roles',
    label: 'Mansioni',
    singularLabel: 'Mansione',
    role: 'Admin',
    readEndpoint: '/api/master-data/job-roles',
    createEndpoint: '/api/admin-data/job-roles',
    updateEndpoint: '/api/admin-data/job-roles',
    deleteEndpoint: '/api/admin-data/job-roles',
    idField: 'id',
    fields: [
      { name: 'name', label: 'Nome mansione', type: 'text', required: true, minLength: 2, maxLength: 120, placeholder: 'Es. Operatore linea' },
      { name: 'description', label: 'Descrizione', type: 'textarea', required: false, maxLength: 500, placeholder: 'Descrizione operativa mansione.' },
      { name: 'periodicitaVisita', label: 'Periodicità Visita', type: 'select', required: false, options: [{ value: 'Annuale', label: 'Annuale' }, { value: 'Biennale', label: 'Biennale' }, { value: 'Triennale', label: 'Triennale' }, { value: 'Quinquennale', label: 'Quinquennale' }] },
      { name: 'limiteEta', label: 'Limite Età', type: 'number', required: false, min: 0, max: 100 },
      { name: 'periodicitaLimiteEta', label: 'Periodicità Limite Età', type: 'select', required: false, options: [{ value: 'Annuale', label: 'Annuale' }, { value: 'Biennale', label: 'Biennale' }] },
      { name: 'protocolloRuolo', label: 'Protocollo di Ruolo', type: 'text', required: false, maxLength: 250 },
      { name: 'visitaFineRapporto', label: 'Visita Fine Rapporto', type: 'text', required: false, maxLength: 250 },
      { name: 'dlgs271', label: 'D.Lgs 271/99', type: 'text', required: false, maxLength: 250 },
      { name: 'dm88', label: 'DM 88/99', type: 'text', required: false, maxLength: 250 },
    ],
  },
  {
    key: 'protocols-registry',
    label: 'Protocolli Normativi',
    singularLabel: 'Protocollo Normativo',
    role: 'Admin',
    readEndpoint: '/api/master-data/protocols',
    createEndpoint: '/api/admin-data/protocols',
    updateEndpoint: '/api/admin-data/protocols',
    deleteEndpoint: '/api/admin-data/protocols',
    idField: 'id',
    fields: [
      { name: 'name', label: 'Nome protocollo', type: 'text', required: true, minLength: 2, maxLength: 160, placeholder: 'Es. Protocollo operatore linea' },
      { name: 'lawReference', label: 'Riferimento normativo', type: 'text', required: true, minLength: 2, maxLength: 30, placeholder: 'Es. 81/08, 101/20' },
      { name: 'cadenceDays', label: 'Cadenza (giorni)', type: 'number', required: true, min: 1, max: 3650, placeholder: 'Es. 365' },
      { name: 'objective', label: 'Obiettivo', type: 'textarea', required: false, maxLength: 1000, placeholder: 'Obiettivo clinico del protocollo' },
      { name: 'jobRoleId', label: 'Mansione', type: 'select', required: false, optionsEndpoint: '/api/master-data/job-roles', optionValue: 'id', optionLabel: 'name' },
    ],
  },
  {
    key: 'personal-protocols',
    label: 'Protocolli Personali',
    singularLabel: 'Protocollo Personale',
    role: 'Admin',
    readEndpoint: '/api/master-data/personal-protocols',
    createEndpoint: '/api/admin-data/personal-protocols',
    updateEndpoint: '/api/admin-data/personal-protocols',
    deleteEndpoint: '/api/admin-data/personal-protocols',
    idField: 'id',
    fields: [
      { name: 'employeeId', label: 'Dipendente', type: 'select', required: true, optionsEndpoint: '/api/master-data/employees', optionValue: 'id', optionLabel: 'lastName' },
      { name: 'protocolId', label: 'Protocollo', type: 'select', required: true, optionsEndpoint: '/api/master-data/protocols', optionValue: 'id', optionLabel: 'name' },
      { name: 'assignedAt', label: 'Data assegnazione', type: 'date', required: true },
      {
        name: 'isOverride',
        label: 'Override',
        type: 'select',
        required: true,
        options: [
          { value: true, label: 'Sì' },
          { value: false, label: 'No' },
        ],
      },
      { name: 'notes', label: 'Note', type: 'textarea', required: false, maxLength: 1000, placeholder: 'Motivazione o dettaglio override' },
    ],
  },
  {
    key: 'employee-risks',
    label: 'Rischi Dipendente',
    singularLabel: 'Rischio Dipendente',
    role: 'Admin',
    readEndpoint: '/api/master-data/employee-risks',
    createEndpoint: '/api/admin-data/employee-risks',
    updateEndpoint: '/api/admin-data/employee-risks',
    deleteEndpoint: '/api/admin-data/employee-risks',
    compositeKey: ['employeeId', 'riskFactorId'],
    fields: [
      { name: 'employeeId', label: 'Dipendente', type: 'select', required: true, optionsEndpoint: '/api/master-data/employees', optionValue: 'id', optionLabel: 'lastName' },
      { name: 'riskFactorId', label: 'Fattore di Rischio', type: 'select', required: true, optionsEndpoint: '/api/master-data/risk-factors', optionValue: 'id', optionLabel: 'name' },
    ],
  },
  {
    key: 'medical-records',
    label: 'Cartelle Sanitarie',
    singularLabel: 'Cartella Sanitaria',
    role: 'Doctor',
    readEndpoint: '/api/master-data/medical-records',
    createEndpoint: '/api/doctor-data/medical-records',
    updateEndpoint: '/api/doctor-data/medical-records',
    deleteEndpoint: '/api/doctor-data/medical-records',
    idField: 'id',
    fields: [
      { name: 'employeeId', label: 'Dipendente', type: 'select', required: true, optionsEndpoint: '/api/master-data/employees', optionValue: 'id', optionLabel: 'lastName' },
      { name: 'medicalHistory', label: 'Anamnesi', type: 'textarea', required: true, minLength: 20, maxLength: 4000, placeholder: 'Inserisci anamnesi lavorativa e clinica rilevante...' },
      { name: 'notes', label: 'Note Cliniche', type: 'textarea', required: false, maxLength: 2000, placeholder: 'Note integrative, prescrizioni o monitoraggi consigliati.' },
      { name: 'currentTherapies', label: 'Terapie in Corso', type: 'textarea', required: false, maxLength: 2000, placeholder: 'Es. Nessuna terapia / farmaci in uso...' },
      {
        name: 'status',
        label: 'Stato cartella',
        type: 'select',
        required: true,
        options: [
          { value: 'Active', label: 'Active' },
          { value: 'Suspended', label: 'Suspended' },
          { value: 'Closed', label: 'Closed' },
        ],
      },
    ],
  },
  {
    key: 'medical-visits',
    label: 'Visite Mediche',
    singularLabel: 'Visita Medica',
    role: 'Doctor',
    readEndpoint: '/api/master-data/medical-visits',
    createEndpoint: '/api/doctor-data/medical-visits',
    updateEndpoint: '/api/doctor-data/medical-visits',
    deleteEndpoint: '/api/doctor-data/medical-visits',
    idField: 'id',
    customValidate: (formData) => {
      const errors = {}
      if (formData.visitDate && formData.nextDeadlineDate) {
        const visit = new Date(formData.visitDate)
        const deadline = new Date(formData.nextDeadlineDate)
        if (deadline < visit) {
          errors.nextDeadlineDate = 'La scadenza deve essere uguale o successiva alla data visita.'
        }
      }
      return errors
    },
    fields: [
      { name: 'employeeId', label: 'Dipendente', type: 'select', required: true, optionsEndpoint: '/api/master-data/employees', optionValue: 'id', optionLabel: 'lastName' },
      { name: 'doctorId', label: 'Medico', type: 'select', required: true, optionsEndpoint: '/api/master-data/doctors', optionValue: 'id', optionLabel: 'lastName' },
      { name: 'visitDate', label: 'Data Visita', type: 'date', required: true },
      { name: 'nextDeadlineDate', label: 'Prossima Scadenza', type: 'date', required: true },
      {
        name: 'visitType',
        label: 'Tipologia Visita',
        type: 'select',
        required: true,
        options: [
          { value: 'Preventive', label: 'Preventive' },
          { value: 'Periodic', label: 'Periodic' },
          { value: 'RoleChange', label: 'RoleChange' },
          { value: 'EmployeeRequest', label: 'EmployeeRequest' },
          { value: 'EndOfRelationship', label: 'EndOfRelationship' },
        ],
      },
      { name: 'outcome', label: 'Esito', type: 'text', required: true, minLength: 3, maxLength: 250, placeholder: 'Es. Idoneo con prescrizioni' },
      { name: 'targetOrgans', label: 'Organi Bersaglio', type: 'textarea', required: false, maxLength: 2000, placeholder: 'Es. Apparato respiratorio, udito' },
      { name: 'objectiveExam', label: 'Esame Obiettivo', type: 'textarea', required: false, maxLength: 4000, placeholder: 'Descrizione esame obiettivo effettuato' },
      { name: 'clinicalNotes', label: 'Note Cliniche', type: 'textarea', required: false, maxLength: 4000, placeholder: 'Annotazioni cliniche, DPI consigliati, frequenza controlli...' },
    ],
  },
  {
    key: 'anamneses',
    label: 'Anamnesi guidata',
    singularLabel: 'Anamnesi',
    role: 'Doctor',
    readEndpoint: '/api/master-data/anamneses',
    createEndpoint: '/api/doctor-data/anamneses',
    updateEndpoint: '/api/doctor-data/anamneses',
    deleteEndpoint: '/api/doctor-data/anamneses',
    idField: 'id',
    fields: [
      { name: 'medicalVisitId', label: 'Visita medica', type: 'select', required: true, optionsEndpoint: '/api/master-data/medical-visits', optionValue: 'id', optionLabel: 'outcome' },
      { name: 'workHistory', label: 'Storia lavorativa', type: 'textarea', required: false, maxLength: 4000 },
      { name: 'personalHistory', label: 'Storia personale', type: 'textarea', required: false, maxLength: 4000 },
      { name: 'familyHistory', label: 'Storia familiare', type: 'textarea', required: false, maxLength: 4000 },
      { name: 'remotePathology', label: 'Patologie remote', type: 'textarea', required: false, maxLength: 4000 },
      { name: 'recentPathology', label: 'Patologie recenti', type: 'textarea', required: false, maxLength: 4000 },
    ],
  },
  {
    key: 'exam-types',
    label: 'Tipi Esame',
    singularLabel: 'Tipo Esame',
    role: 'Admin',
    readEndpoint: '/api/master-data/exam-types',
    createEndpoint: '/api/admin-data/exam-types',
    updateEndpoint: '/api/admin-data/exam-types',
    deleteEndpoint: '/api/admin-data/exam-types',
    idField: 'id',
    fields: [
      { name: 'name', label: 'Nome Esame', type: 'text', required: true, minLength: 2, maxLength: 120, placeholder: 'Es. Spirometria' },
      { name: 'category', label: 'Categoria', type: 'text', required: false, maxLength: 120, placeholder: 'Es. Funzionale Respiratorio' },
    ],
  },
  {
    key: 'visit-exams',
    label: 'Esami Visita',
    singularLabel: 'Esame Visita',
    role: 'Doctor',
    readEndpoint: '/api/master-data/visit-exams',
    createEndpoint: '/api/doctor-data/visit-exams',
    updateEndpoint: '/api/doctor-data/visit-exams',
    deleteEndpoint: '/api/doctor-data/visit-exams',
    idField: 'id',
    fields: [
      { name: 'medicalVisitId', label: 'Visita Medica', type: 'select', required: true, optionsEndpoint: '/api/master-data/medical-visits', optionValue: 'id', optionLabel: 'outcome' },
      { name: 'examTypeId', label: 'Tipo Esame', type: 'select', required: true, optionsEndpoint: '/api/master-data/exam-types', optionValue: 'id', optionLabel: 'name' },
      { name: 'referenceRange', label: 'Intervallo di Riferimento', type: 'text', required: false, maxLength: 300, placeholder: 'Es. FEV1 > 80%' },
      { name: 'result', label: 'Risultato', type: 'textarea', required: true, minLength: 2, maxLength: 3000, placeholder: 'Inserisci il risultato clinico dell’esame...' },
      { name: 'notes', label: 'Note', type: 'textarea', required: false, maxLength: 2000, placeholder: 'Eventuali note di dettaglio.' },
    ],
  },
  {
    key: 'scheduled-exams',
    label: 'Accertamenti programmati',
    singularLabel: 'Accertamento programmato',
    role: 'Doctor',
    readEndpoint: '/api/master-data/scheduled-exams',
    createEndpoint: '/api/doctor-data/scheduled-exams',
    updateEndpoint: '/api/doctor-data/scheduled-exams',
    deleteEndpoint: '/api/doctor-data/scheduled-exams',
    idField: 'id',
    fields: [
      { name: 'employeeId', label: 'Dipendente', type: 'select', required: true, optionsEndpoint: '/api/master-data/employees', optionValue: 'id', optionLabel: 'lastName' },
      { name: 'examTypeId', label: 'Tipo esame', type: 'select', required: true, optionsEndpoint: '/api/master-data/exam-types', optionValue: 'id', optionLabel: 'name' },
      { name: 'dueDate', label: 'Scadenza', type: 'date', required: true },
      {
        name: 'status',
        label: 'Stato',
        type: 'select',
        required: true,
        options: [
          { value: 'Planned', label: 'Planned' },
          { value: 'Completed', label: 'Completed' },
          { value: 'Cancelled', label: 'Cancelled' },
        ],
      },
    ],
  },
  {
    key: 'vaccinations',
    label: 'Vaccinazioni',
    singularLabel: 'Vaccinazione',
    role: 'Doctor',
    readEndpoint: '/api/master-data/vaccinations',
    createEndpoint: '/api/doctor-data/vaccinations',
    updateEndpoint: '/api/doctor-data/vaccinations',
    deleteEndpoint: '/api/doctor-data/vaccinations',
    idField: 'id',
    fields: [
      { name: 'employeeId', label: 'Dipendente', type: 'select', required: true, optionsEndpoint: '/api/master-data/employees', optionValue: 'id', optionLabel: 'lastName' },
      { name: 'vaccineName', label: 'Vaccino', type: 'text', required: true, minLength: 2, maxLength: 150 },
      { name: 'dateAdministered', label: 'Data somministrazione', type: 'date', required: true },
      { name: 'nextDueDate', label: 'Prossima scadenza', type: 'date', required: false },
    ],
  },
  {
    key: 'company-groups',
    label: 'Gruppi Aziendali',
    singularLabel: 'Gruppo Aziendale',
    role: 'Admin',
    readEndpoint: '/api/master-data/company-groups',
    createEndpoint: '/api/admin-data/company-groups',
    updateEndpoint: '/api/admin-data/company-groups',
    deleteEndpoint: '/api/admin-data/company-groups',
    idField: 'id',
    fields: [
      { name: 'name', label: 'Nome Gruppo Aziendale', type: 'text', required: true, minLength: 2, maxLength: 200, placeholder: 'Es. Gruppo Acme' },
      { name: 'legalName', label: 'Ragione Sociale', type: 'text', required: false, minLength: 2, maxLength: 200, placeholder: 'Es. GRUPPO ACME SPA' },
      { name: 'address', label: 'Indirizzo', type: 'text', required: false, maxLength: 250 },
      { name: 'city', label: 'Città', type: 'text', required: false, maxLength: 100 },
      { name: 'cap', label: 'CAP', type: 'text', required: false, maxLength: 10 },
      { name: 'province', label: 'Provincia', type: 'text', required: false, maxLength: 100 },
      { name: 'vatNumber', label: 'Partita IVA', type: 'text', required: false, minLength: 11, maxLength: 13, pattern: VAT_NUMBER_REGEX, patternMessage: 'Inserisci 11 cifre o formato IT + 11 cifre.', placeholder: 'Es. IT01234567890' },
      { name: 'taxCode', label: 'Codice Fiscale', type: 'text', required: false, maxLength: 16, placeholder: 'Es. 00123456789012' },
      { name: 'singleArchive', label: 'Archivio Documentale Unico', type: 'select', required: false, defaultValue: false, optionValue: 'value', optionLabel: 'label', options: [{ value: true, label: 'Sì' }, { value: false, label: 'No' }], transform: (v) => v === true || v === 'true' || v === 'on' },
    ],
  },
  {
    key: 'company-contacts',
    label: 'Figure Aziendali',
    singularLabel: 'Figura Aziendale',
    role: 'Admin',
    readEndpoint: '/api/master-data/company-contacts',
    createEndpoint: '/api/admin-data/company-contacts',
    updateEndpoint: '/api/admin-data/company-contacts',
    deleteEndpoint: '/api/admin-data/company-contacts',
    idField: 'id',
    fields: [
      { name: 'companyId', label: 'Azienda', type: 'select', required: true, optionsEndpoint: '/api/master-data/companies', optionValue: 'id', optionLabel: 'name' },
      { name: 'ruolo', label: 'Ruolo Aziendale', type: 'select', required: true, options: [{ value: 'RSPP', label: 'RSPP' }, { value: 'RLS', label: 'RLS' }, { value: 'DL', label: 'Datore di Lavoro' }, { value: 'Dirigente', label: 'Dirigente' }] },
      { name: 'nominativo', label: 'Nominativo', type: 'text', required: true, minLength: 2, maxLength: 150 },
      { name: 'email', label: 'Email', type: 'email', required: false, maxLength: 150 },
      { name: 'telefono', label: 'Telefono', type: 'tel', required: false, maxLength: 30 },
    ],
  },
  {
    key: 'departments',
    label: 'Reparti',
    singularLabel: 'Reparto',
    role: 'Admin',
    readEndpoint: '/api/master-data/departments',
    createEndpoint: '/api/admin-data/departments',
    updateEndpoint: '/api/admin-data/departments',
    deleteEndpoint: '/api/admin-data/departments',
    idField: 'id',
    fields: [
      { name: 'companyId', label: 'Azienda', type: 'select', required: true, optionsEndpoint: '/api/master-data/companies', optionValue: 'id', optionLabel: 'name' },
      { name: 'nome', label: 'Nome Reparto', type: 'text', required: true, minLength: 2, maxLength: 150 },
      { name: 'referente', label: 'Referente', type: 'text', required: false, maxLength: 150 },
      { name: 'emailReferente', label: 'Email Referente', type: 'email', required: false, maxLength: 150 },
      { name: 'attivo', label: 'Attivo', type: 'text', required: false, maxLength: 50 },
    ],
  },
  {
    key: 'work-locations',
    label: 'Luoghi di Lavoro',
    singularLabel: 'Luogo di Lavoro',
    role: 'Admin',
    readEndpoint: '/api/master-data/work-locations',
    createEndpoint: '/api/admin-data/work-locations',
    updateEndpoint: '/api/admin-data/work-locations',
    deleteEndpoint: '/api/admin-data/work-locations',
    idField: 'id',
    fields: [
      { name: 'companyId', label: 'Azienda', type: 'select', required: true, optionsEndpoint: '/api/master-data/companies', optionValue: 'id', optionLabel: 'name' },
      { name: 'descrizione', label: 'Descrizione', type: 'text', required: true, minLength: 2, maxLength: 250 },
      { name: 'citta', label: 'Città', type: 'text', required: false, maxLength: 100 },
      { name: 'cap', label: 'CAP', type: 'text', required: false, maxLength: 10 },
      { name: 'provincia', label: 'Provincia', type: 'text', required: false, maxLength: 100 },
      { name: 'attivo', label: 'Attivo', type: 'text', required: false, maxLength: 50 },
    ],
  },
  {
    key: 'site-visits',
    label: 'Sopralluoghi',
    singularLabel: 'Sopralluogo',
    role: 'Doctor',
    readEndpoint: '/api/master-data/site-visits',
    createEndpoint: '/api/doctor-data/site-visits',
    updateEndpoint: '/api/doctor-data/site-visits',
    deleteEndpoint: '/api/doctor-data/site-visits',
    idField: 'id',
    fields: [
      { name: 'companyId', label: 'Azienda', type: 'select', required: true, optionsEndpoint: '/api/master-data/companies', optionValue: 'id', optionLabel: 'name' },
      { name: 'strutturaVisitata', label: 'Struttura Visitata', type: 'text', required: true, minLength: 2, maxLength: 250 },
      { name: 'luogo', label: 'Luogo', type: 'text', required: false, maxLength: 250 },
      { name: 'medico', label: 'Medico', type: 'text', required: false, maxLength: 150 },
      { name: 'data', label: 'Data', type: 'date', required: true },
      { name: 'periodicita', label: 'Periodicità', type: 'select', required: false, options: [{ value: 'Annuale', label: 'Annuale' }, { value: 'Biennale', label: 'Biennale' }, { value: 'Triennale', label: 'Triennale' }] },
      { name: 'scadenza', label: 'Scadenza', type: 'date', required: false },
    ],
  },
  {
    key: 'doctor-availabilities',
    label: 'Disponibilita medici',
    singularLabel: 'Disponibilità medico',
    role: 'Doctor',
    readOnly: true,
    readEndpoint: '/api/master-data/doctor-availabilities',
    idField: 'id',
    fields: [
      { name: 'doctorFullName', label: 'Medico', type: 'text', required: false },
      { name: 'dayOfWeek', label: 'Giorno', type: 'text', required: false },
      { name: 'startTime', label: 'Ora inizio', type: 'text', required: false },
      { name: 'endTime', label: 'Ora fine', type: 'text', required: false },
    ],
  },
  {
    key: 'notification-logs',
    label: 'Log notifiche',
    singularLabel: 'Log notifica',
    role: 'Doctor',
    readOnly: true,
    readEndpoint: '/api/master-data/notification-logs',
    idField: 'id',
    fields: [
      { name: 'employeeFullName', label: 'Lavoratore', type: 'text', required: false },
      { name: 'channel', label: 'Canale', type: 'text', required: false },
      { name: 'sentDate', label: 'Data invio', type: 'date', required: false },
      { name: 'messageText', label: 'Messaggio', type: 'textarea', required: false },
    ],
  },
]
